controller_list:
  - name: fake_upper_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - ee_joint
initial:  # Define initial robot poses per group
  - group: upper_arm
    pose: Home