ver5_bokhop:
  hardware_interface:
    joints:
      - ee_joint
      - joint_1
      - joint_2
      - joint_3
      - joint_4

  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  upper_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints: 
      - ee_joint
      - joint_1
      - joint_2
      - joint_3
      - joint_4
  gains:
    joint1: {p: 1.0, i: 0.0, d: 0.1}
    joint2: {p: 1.0, i: 0.0, d: 0.1}
    joint3: {p: 1.0, i: 0.0, d: 0.1}
  