controller_list:
  - name: "/ver5_bokhop/upper_arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - ee_joint
initial:  # Define initial robot poses per group
  - group: upper_arm
    pose: Home